version: '3.4'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      DEV_DB_NAME: atriposaday
      DEV_DB_USERNAME: postgres
      DEV_DB_HOSTNAME: db
      DEV_DB_PASSWORD: password
      NODE_ENV: development
      PORT: 8080
      ATAD_FQDN: localhost
    command: npx nodemon app/server.js
    volumes:
      - ${PWD}:/opt/code
    ports:
      - "8080:8080"
    depends_on:
      - "db"

volumes:
  pgdata:
