module.exports = {
    PAPERS: ["2P1_MECHANICS", "2P2_STRUCTURES", "2P3_MATERIALS", "2P4_THERMOFLUID_MECHANICS", "2P5_ELECTRICAL_ENGINEERING", "2P6_INFORMATION_ENGINEERING", "2P7_MATHEMATICAL_METHODS", "2P8_SELECTED_TOPICS"]
}